### ISSUE TITLE
преобразование файлов между форматами OWL и XML

### ISSUE THREAD

**Issue by kinnder** [kinnder/process-engineering#47]
Необходимо разработать команду позволяющую переводить файлы из формата XML в формат OWL и обратно

**Comment by kinnder** [comment]
java -jar .\application-0.1.0.jar -convert -td "al_nn.owl" -st "al_st.owl" -nn "al_nn.owl" -p "al_p.owl"

[ERROR] 2021-11-17 17:32:25.195 [main] Main -
java.lang.NullPointerException: Cannot invoke "planning.model.System.getObjects()" because "system" is null
        at application.storage.xml.SystemXMLSchema.combine(SystemXMLSchema.java:53) ~[application-0.1.0.jar:?]
        at application.storage.xml.TaskDescriptionXMLSchema.combine(TaskDescriptionXMLSchema.java:52) ~[application-0.1.0.jar:?]
        at application.storage.xml.TaskDescriptionXMLSchema.combine(TaskDescriptionXMLSchema.java:1) ~[application-0.1.0.jar:?]
        at application.storage.xml.XMLFile.save(XMLFile.java:61) ~[application-0.1.0.jar:?]
        at application.storage.xml.XMLFile.save(XMLFile.java:53) ~[application-0.1.0.jar:?]
        at application.storage.PersistanceStorage.saveTaskDescription(PersistanceStorage.java:80) ~[application-0.1.0.jar:?]
        at application.Application.saveTaskDescription(Application.java:81) ~[application-0.1.0.jar:?]
        at application.command.ConvertCommand.execute(ConvertCommand.java:31) ~[application-0.1.0.jar:?]
        at application.command.ConvertCommand.execute(ConvertCommand.java:22) ~[application-0.1.0.jar:?]
        at application.Application.runCommand(Application.java:198) ~[application-0.1.0.jar:?]
        at application.Application.run(Application.java:187) ~[application-0.1.0.jar:?]
        at application.Main.main(Main.java:12) [application-0.1.0.jar:?]

**Comment by kinnder** [comment]
ошибка возникла из-за неправильной команды, правильная команда выглядит: 
java -jar .\application-0.1.0.jar -convert -td "al_td.owl" -st "al_st.owl" -nn "al_nn.owl" -p "al_p.owl"
